# shellcheck shell=bash
# plasmashell's side of a switch: the two shell packages, changing to one of
# them live, the panel's geometry, and keeping safe the layout of the package
# being left.
#
# Sourced by renderer.sh, never executed. Requires brand.sh, log.sh,
# render.sh, kconfig.sh, appletsrc.sh, renderers.sh and lockscreen.sh, and
# the BACKUP_DIR renderer.sh names.
#
# Whether this run may touch the running desktop at all.
#
# A throwaway HOME does not give a throwaway session bus: plasmashell is still
# listening on the real one, and `changeShell` would switch the desktop the
# person is using while a test believed it was working in a sandbox. So the
# guard is explicit -- `session_available`, in brand.sh -- and the tests set it.

# --- package installation --------------------------------------------------

# Installs one shell package. Both are installed whenever either is needed:
# switching back must not depend on an install step that could fail at the
# worst moment, with the old layout already gone.
install_shell_package() {
    local src=$1 id=$2
    local dest="$PLASMA_SHELLS_DIR/$id"

    mkdir -p "$dest/contents"
    render_template "$src/metadata.json.in" "$dest/metadata.json" \
        || { log_error "could not render the metadata for $id"; return 1; }
    chmod 644 "$dest/metadata.json"

    cp -a "$src/contents/layouts" "$dest/contents/" || return 1
    cp -a "$src/contents/defaults" "$dest/contents/" || return 1

    # The lock screen, when it is on, lives inside the package, so one
    # installed afresh gets it back. See lockscreen.sh.
    if lockscreen_enabled && [ ! -e "$dest/contents/lockscreen" ]; then
        lockscreen_install_into "$id" || log_warn "could not put the lock screen back into $id"
    fi
    log_debug "installed $dest"
}

install_packages() {
    install_shell_package "$REPO_ROOT/plasma/shells/quickshell" "$SHELL_PACKAGE_ID" || return 1
    install_shell_package "$REPO_ROOT/plasma/shells/plasma"     "$PLASMA_SHELL_PACKAGE_ID" || return 1
    # KDE caches installed packages; without this plasmashell cannot resolve
    # the package we are about to point it at until the next login.
    session_available && kbuildsycoca6 --noincremental >/dev/null 2>&1
    true
    log_step "installed both shell packages in $PLASMA_SHELLS_DIR"
}

# --- protecting the layout we are switching away from ----------------------
#
# Observed on a live desktop: switching ShellPackage away from a third-party
# package left that package's applet layout gutted -- every containment gone,
# the panel and desktop it described with them. plasmashell had written its own
# now-empty view of that package's config back to disk on the way out.
#
# It is not our write, but it happens because of our switch, and "it was
# plasmashell" is no comfort to someone whose panel layout has just been
# deleted. So the outgoing layout is copied out before the switch and put back
# if it comes out the other side with fewer containments than it went in with.
OUTGOING_PKG=""
OUTGOING_COPY=""
OUTGOING_COUNT=0

hold_outgoing_layout() {
    OUTGOING_PKG=$(live_shell_package)
    OUTGOING_COPY=""
    OUTGOING_COUNT=0

    # Our own layouts are regenerated by this command anyway, and the stock
    # package is never modified by anyone here.
    case "$OUTGOING_PKG" in
        "$SHELL_PACKAGE_ID"|"$PLASMA_SHELL_PACKAGE_ID"|org.kde.plasma.desktop) return 0 ;;
    esac

    local held
    held=$(appletsrc_hold "$OUTGOING_PKG" "$BACKUP_DIR/outgoing") || return 0
    [ -n "$held" ] || return 0
    OUTGOING_COUNT=${held%% *}
    OUTGOING_COPY=${held#* }
    log_debug "holding $OUTGOING_PKG's layout ($OUTGOING_COUNT containment(s))"
}

restore_outgoing_layout() {
    appletsrc_restore_if_gutted "$OUTGOING_PKG" "$OUTGOING_COPY" "$OUTGOING_COUNT"
}

# --- switching -------------------------------------------------------------

# Asks plasmashell to change shell live, then confirms it stuck. The DBus call
# is preferred because it needs no restart; the key write is the fallback, not
# the primary path, because a key write alone does nothing until the next login
# and the user would be left looking at the old panel wondering what happened.
CHANGESHELL_OK=0

apply_shell_package() {
    local pkg=$1

    if session_available \
       && qdbus6 org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.changeShell "$pkg" >/dev/null 2>&1; then
        CHANGESHELL_OK=1
        log_debug "changeShell($pkg) accepted"
    else
        log_debug "changeShell is unavailable (plasmashell may not be running)"
    fi

    # Written either way: changeShell does not always persist the choice, and
    # the ledger is what makes it undoable.
    kconfig_set backend plasmashellrc Shell ShellPackage "$pkg"

    local live
    live=$(live_shell_package)
    if [ "$live" != "$pkg" ]; then
        log_error "plasmashell's shell package is '$live', expected '$pkg'"
        return 1
    fi
}

# The panel view's geometry lives in plasmashellrc, keyed by the containment id
# we allocate, not in the applet layout. Writing it means a thickness set in our
# settings window reaches the Plasma panel too.
#
# It happens AFTER the switch, and through the running plasmashell as well as
# the key. plasmashell creates the panel view when it loads the package and
# holds its geometry in memory, so a key written beforehand is not what ends up
# on screen and a thickness change would appear to do nothing until the next
# start.
apply_panel_geometry() {
    local pkg=$1 thickness=$2 position=$3
    local group="PlasmaViews/Panel $APPLETSRC_PANEL_ID"
    kconfig_set backend plasmashellrc "$group" shell "$pkg"
    kconfig_set backend plasmashellrc "$group/Defaults" thickness "$thickness"

    session_available || return 0

    # And tell the running plasmashell, which holds the view in memory and
    # writes its own value back over ours otherwise.
    #
    # changeShell returns before the new package's panel exists, so this waits
    # for it. Without the wait the assignment lands on an empty list and does
    # nothing at all -- which looks exactly like the key write being ignored.
    # Break only on a positive count. An empty answer -- plasmashell still
    # starting, or the call failing outright -- is not "the panel is ready",
    # and treating it as one is exactly how the assignment landed on an empty
    # list and did nothing.
    local waited=0 count
    while [ "$waited" -lt 20 ]; do
        count=$(_plasma_script 'print(panels().length)')
        case "$count" in ''|*[!0-9]*) count=0 ;; esac
        [ "$count" -gt 0 ] && break
        sleep 0.25
        waited=$((waited + 1))
    done
    # The containment exists a moment before the view that draws it does.
    sleep 0.5

    # A vertical panel's thickness is its width; a horizontal one's is its
    # height, and the scripting API has no single name for it.
    local prop=height
    case "$position" in left|right) prop=width ;; esac

    if ! _plasma_script "panels().forEach(function (p) { p.$prop = $thickness; })" >/dev/null; then
        log_warn "could not set the panel thickness through plasmashell"
        log_info "  it will be $thickness after the next plasmashell start"
    fi
}

# plasmashell's own scripting console, over DBus. Returns whatever the script
# printed.
_plasma_script() {
    qdbus6 org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "$1" 2>/dev/null
}

restart_plasmashell() {
    session_available || { log_debug "not touching the session"; return 0; }
    # kquitapp6 is wrong here: the unit is Restart=on-failure, so a clean exit
    # leaves plasmashell dead and the user with no desktop at all.
    if systemctl --user restart plasma-plasmashell.service >/dev/null 2>&1; then
        log_step "restarted plasmashell"
    else
        log_warn "could not restart plasmashell; log out and back in to see the change"
    fi
}
