#!/usr/bin/env bash
# Generates shell/core/Branding.qml from branding.json and VERSION.
#   gen-branding.sh [--check]
#
# QML never reads branding.json at runtime: it gets a typed singleton with no
# file I/O on the hot path. Regenerated by `make brand`, `make link`, the
# installer and CI.
#
# What it holds is the project's identity, the same on every machine -- and
# only that, which is why it is committed. It used to hold where this machine
# keeps things as well, generated per user into the tree the live shell runs
# from, and three things went wrong with that file in the shape it had: a
# sandbox install wrote sandbox paths into it, the preview had to patch it to
# move anything, and `make clean` deleted it, which left the next login with no
# shell at all (2026-10-08). Where things are is worked out when the shell
# starts now, in core/Paths.qml.
#
# --check writes nothing and fails if the committed file is not what this
# would write; it is how scripts/lint-generated.sh keeps the two together.
set -euo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
source "$REPO_ROOT/scripts/lib/log.sh"
source "$REPO_ROOT/scripts/lib/brand.sh"
source "$REPO_ROOT/scripts/lib/render.sh"
source "$REPO_ROOT/scripts/lib/generated.sh"

[ "${1:-}" = --check ] && GEN_CHECK=1

out="$REPO_ROOT/shell/core/Branding.qml"

write_generated "$out" <<EOF
pragma Singleton

// GENERATED FILE -- DO NOT EDIT.
// Source: branding.json, VERSION          Regenerate: scripts/gen-branding.sh
//
// The project name is a variable, not a constant. Nothing outside this file
// and branding.json may contain the literal slug; scripts/lint-slug.sh enforces it.
//
// Committed, and identity only: nothing here depends on the machine. Where
// this machine keeps things is core/Paths.qml.

import QtQuick

QtObject {
    readonly property string slug: "$SLUG"
    readonly property string shortName: "$ALIAS"
    readonly property string displayName: "$DISPLAY_NAME"
    readonly property string appId: "$APP_ID"
    readonly property string dbusName: "$DBUS_NAME"
    readonly property string envPrefix: "$ENV_PREFIX"
    readonly property string shellPackageId: "$SHELL_PACKAGE_ID"
    readonly property string version: "$VERSION"

    // The control binary's name. Where it is installed is Paths.ctlBin.
    readonly property string ctlName: "$CTL_BIN"

    readonly property string safeModeVar: "$SAFE_MODE_VAR"
    readonly property string debugVar: "$DEBUG_VAR"
}
EOF

[ "${GEN_CHECK:-0}" = 1 ] && exit 0
log_step "generated $out"

# The lock screen's own settings singleton. It names this shell's config
# directory, which is branding, and it is generated here for the same reason
# Branding.qml is: nothing in a QML file may spell the project's name. It is
# per machine, so it stays gitignored; the lock screen is a package of its own,
# installed by copy, and the shell does not read it.
render_template "$REPO_ROOT/theme/lockscreen/Options.qml.in" "$REPO_ROOT/theme/lockscreen/Options.qml"
log_step "generated $REPO_ROOT/theme/lockscreen/Options.qml"
