#!/usr/bin/env bash
# Regenerates theme/colors/palette.json from the shell's own Material scheme,
# then the colour schemes from it.
#
# Two palettes in two languages is one palette too many. The shell computes
# its colours in Scheme.qml -- Material 3 roles from one seed, tested -- and
# Plasma's colour scheme is that same set of colours, named the way Plasma
# names them. So this asks the shell rather than reimplementing the maths:
# quickshell is already what draws this project, and it runs offscreen, with
# no display and nothing on screen.
#
# Not part of `make brand`: it needs quickshell and takes a second, and the
# palette only changes when the scheme does. Run it after changing Scheme.qml,
# and commit what it writes.
set -euo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
source "$REPO_ROOT/scripts/lib/log.sh"
source "$REPO_ROOT/scripts/lib/brand.sh"

command -v quickshell >/dev/null 2>&1 || die "quickshell is needed to read the scheme"
[ -f "$REPO_ROOT/shell/core/Branding.qml" ] || "$REPO_ROOT/scripts/gen-branding.sh" >/dev/null

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
cp -r "$REPO_ROOT/shell/." "$work/"
cp "$REPO_ROOT/theme/colors/dump.qml" "$work/dump.qml"

# quickshell does not act on Qt.quit -- the engine says so and keeps running
# -- so the run is stopped by its timeout and read from a file afterwards.
# Piping it into grep instead would make the whole pipeline wait out the
# timeout and then fail on it, which is what happened the first time.
env -u WAYLAND_DISPLAY -u DISPLAY QT_QPA_PLATFORM=offscreen QT_FORCE_STDERR_LOGGING=1 \
    PALETTE_SEED="${PALETTE_SEED:-blue}" \
    timeout 15 quickshell -n -p "$work/dump.qml" > "$work/out.log" 2>&1 || true
out=$(grep -o 'PALETTE {.*}' "$work/out.log" | head -1)
[ -n "$out" ] || die "the scheme printed nothing; run it by hand to see why"

printf '%s' "${out#PALETTE }" | jq \
    --arg comment "The two palettes every generated colour scheme is built from. GENERATED by scripts/gen-palette.sh from the shell's own Material scheme (shell/domain/theme/palette/Scheme.qml), so KDE's applications and this shell's own surfaces are drawn in one set of colours rather than two that drift apart. Regenerate after changing the scheme; the accent is the design's blue, because a generated file must be the same on every machine -- the running shell follows Plasma's own accent live." \
    '{comment: $comment, dark: .dark, light: .light}' > "$REPO_ROOT/theme/colors/palette.json"

log_step "wrote $REPO_ROOT/theme/colors/palette.json"
"$REPO_ROOT/scripts/gen-colors.sh"
