#!/usr/bin/env bash
# Generates shell/core/Branding.qml from branding.json.
#
# QML never reads branding.json at runtime: it gets a typed singleton with no
# file I/O on the hot path. Regenerated by `just link`, `just install` and CI.
set -euo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
source "$REPO_ROOT/scripts/lib/log.sh"
source "$REPO_ROOT/scripts/lib/brand.sh"

out="$REPO_ROOT/shell/core/Branding.qml"

cat > "$out" <<EOF
pragma Singleton

// GENERATED FILE -- DO NOT EDIT.
// Source: branding.json          Regenerate: scripts/gen-branding.sh
//
// The project name is a variable, not a constant. Nothing outside this file
// and branding.json may contain the literal slug; scripts/lint-slug.sh enforces it.

import QtQuick

QtObject {
    readonly property string slug: "$SLUG"
    readonly property string shortName: "$ALIAS"
    readonly property string displayName: "$DISPLAY_NAME"
    readonly property string appId: "$APP_ID"
    readonly property string dbusName: "$DBUS_NAME"
    readonly property string envPrefix: "$ENV_PREFIX"
    readonly property string shellPackageId: "$SHELL_PACKAGE_ID"
    readonly property string version: "$VERSION"

    readonly property string configDir: "$CONFIG_DIR"
    readonly property string dataDir: "$DATA_DIR"
    readonly property string stateDir: "$STATE_DIR"
    readonly property string qsConfigDir: "$QS_CONFIG_DIR"

    // KDE's own configuration lives here, and a couple of things need to read
    // it -- which package plasmashell is using, and what that package's panel
    // contains.
    readonly property string xdgConfigDir: "$XDG_CONFIG_HOME"

    // The control binary. Everything the shell asks the CLI to do -- switching
    // renderer, writing a diagnostic report -- runs this, so the shell and the
    // terminal always take the same code path.
    readonly property string ctlBin: "$BIN_DIR/$CTL_BIN"

    readonly property string safeModeVar: "$SAFE_MODE_VAR"
    readonly property string debugVar: "$DEBUG_VAR"
}
EOF

log_step "generated $out"
